
[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.production]
  environment = { SECRETS_SCAN_OMIT_KEYS = "ADMIN_PW" }
